services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker  # Activate 'docker' profile
    networks:
      - app-network
    depends_on:
      - db  # Ensure db starts before the app

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: roulette-tracker-db
    ports:
      - "5432:5432"  # Optional if you want to access the DB outside Docker
    networks:
      - app-network

networks:
  app-network: