name: CI Pipeline with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon

      - name: Test with Gradle
        run: ./gradlew test --no-daemon

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and start services using Docker Compose
        run: docker-compose up -d --build

      - name: Wait for services to be ready
        run: |
          sleep 10

      - name: Run tests in the app container
        run: docker-compose exec app ./gradlew test

      - name: Stop and clean up services
        run: docker-compose down --volumes